modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/Traben-0/Entity_Texture_Features/issues"
license = "LGPL-3.0"
showAsResourcePack = false

[[mods]]
modId = "entity_model_features"
version = "${version}"
displayName = "Entity Model Features"
authors = "Traben"
description = '''
This is an expansion of the ETF mod, it adds support for OptiFine format Custom Entity Model (CEM) resource packs.
While still allowing to you disable this to use a different model mod :)
'''
logoFile = "icon.png"

[[dependencies.entity_model_features]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.entity_model_features]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.entity_model_features]]
modId = "entity_texture_features"
mandatory = true
versionRange = "[5.2,)"
ordering = "NONE"
side = "CLIENT"

